/**
 * build-apply-all.ts — emit `supabase/apply-all.sql`, the ONE ordered apply artifact (P0-C6).
 *
 * THE FOOTGUN THIS CLOSES. The per-file migrations + seeds are NOT safe to apply in filename order.
 * The whole non-linear back half depends on migration 0006 (adds `puzzles.requires_flags`) and 0007
 * (adds `puzzles.answer_kind`, which puzzles_seed.sql's second insert names) landing BEFORE the
 * seeds. metapuzzle_seed.sql / progression_seed.sql wrap their activation UPDATEs in a
 * `do $$ … if column exists … else raise exception … $$` guard: apply them before 0006 and the
 * seed batch ABORTS (the guards now fail LOUD, not silent). And if a mis-order ever slipped past,
 * `base-docket-reread-auto` — which ships active=true — would keep its default empty requires_flags
 * and LEAK its four M4 docket answers from minute one. Only a correct, enforced order is safe.
 *
 * THE ENFORCEMENT. This script concatenates the files in the ONE correct order (below), with clear
 * FILE banners, into `supabase/apply-all.sql`. `npm run db:seed` (and the `db:apply` alias) run it;
 * the operator then applies that single generated file (or pipes it to psql / the Supabase SQL
 * editor). The order is a code artifact here, not tribal knowledge in a comment — so it cannot drift
 * from what actually gets applied, and there is no "apply the loose files in Finder order" path left.
 *
 * SCOPE. This is the full launch database path: dashboard base + lockdown, Discord/oracle schema,
 * public Record/Archive views, seeds, and plugin<->DB repair. Nothing lives in a "paste this extra
 * migration after" appendix anymore. apply-all.sql is idempotent + additive end-to-end (every step
 * is `create … if not exists` / `add column if not exists` / `on conflict` upsert), so it is safe to
 * re-run; re-running is in fact the canonical way to re-seed after an authored edit.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve, relative } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
// src/db -> ../../supabase
const SUPA = resolve(here, '../../supabase');
const REPO = resolve(here, '../../..');

/**
 * THE ENFORCED ORDER. Dashboard 0001-0003 create/seed/lock down the base tables that Discord extends.
 * Discord migrations then create solves, threads, observations, rate-limits, and showrunner locking.
 * Dashboard public views come after their Discord dependencies (v_record needs solves; v_archive needs
 * thread_cards). Seeds follow only after every schema column/gate exists. schema-repair stays last as
 * plugin<->DB column/index reconciliation.
 */
const ORDER: readonly string[] = [
  // ---- dashboard base + security lockdown ----
  'dashboard/supabase/migrations/0001_init.sql',
  'dashboard/supabase/migrations/0002_seed.sql',
  'dashboard/supabase/migrations/0003_lockdown.sql',
  // ---- Discord/oracle migrations (0006/0007/0008 MUST precede the seeds) ----
  'discord/supabase/migrations/0003_discord.sql',
  'discord/supabase/migrations/0004_oracle.sql',
  'discord/supabase/migrations/0005_threads.sql',
  'discord/supabase/migrations/0006_requires_flags.sql',
  'discord/supabase/migrations/0007_answer_kind.sql',
  'discord/supabase/migrations/0008_requires_quorum.sql',
  'discord/supabase/migrations/0009_observations.sql',
  'discord/supabase/migrations/0010_answer_attempts_web_rate_limit.sql',
  'discord/supabase/migrations/0011_showrunner_lock.sql',
  // ---- dashboard public/admin views that depend on the Discord schema ----
  'dashboard/supabase/migrations/0004_v_record.sql',
  'dashboard/supabase/migrations/0005_reconcile_tracker_views.sql',
  'dashboard/supabase/migrations/0006_v_record_theories.sql',
  'dashboard/supabase/migrations/0007_v_archive.sql',
  'dashboard/supabase/migrations/0008_v_archive_flag_gate.sql',
  'dashboard/supabase/migrations/0009_beat_queue_failed_status.sql',
  // ---- seeds (puzzles_seed FIRST; metapuzzle + progression LAST — they gate on 0006/0008 columns) ----
  'discord/supabase/seeds/puzzles_seed.sql',
  'discord/supabase/seeds/seventh_seed.sql',
  'discord/supabase/seeds/thread_tags.sql',
  'discord/supabase/seeds/thread_cards.sql',
  'discord/supabase/seeds/side_quests.sql',
  'discord/supabase/seeds/hints_seed.sql',
  'discord/supabase/seeds/metapuzzle_seed.sql',
  'discord/supabase/seeds/progression_seed.sql',
  // ---- plugin<->DB schema reconciliation (adds columns/indexes the plugin upserts need) ----
  'discord/supabase/schema-repair.sql',
];

const HEADER = `-- ============================================================================
-- THE OBSERVANCE — apply-all.sql  (GENERATED by \`npm run db:seed\` — do not hand-edit)
-- ============================================================================
-- Apply this ONE file (Supabase SQL editor, or: psql "$DATABASE_URL" -f apply-all.sql).
-- It is the ONLY safe apply path: dashboard base + lockdown, Discord/oracle schema, public
-- Record/Archive views, seeds, and schema repair are concatenated in the ENFORCED order below.
-- Migration 0006 (puzzles.requires_flags), 0007 (puzzles.answer_kind), and 0008
-- (puzzles.requires_quorum) land BEFORE every seed. Applying the loose files in filename order
-- instead would (a) trip the fail-loud guards in metapuzzle_seed / progression_seed and abort, or
-- worse, if forced, (b) leave late-game answers ungated.
--
-- Idempotent + additive — safe to re-run. Do not paste extra migrations after this file; if a
-- migration matters for launch, add it to src/db/build-apply-all.ts and regenerate this bundle.
--
-- Ordered contents:
${ORDER.map((p, i) => `--   ${String(i + 1).padStart(2, '0')}. ${p}`).join('\n')}
-- ============================================================================

`;

const parts: string[] = [HEADER];
for (const rel of ORDER) {
  const abs = resolve(REPO, rel);
  let body: string;
  try {
    body = readFileSync(abs, 'utf8');
  } catch {
    console.error(`db:seed FAILED — missing required file in the apply order: ${rel}`);
    process.exit(1);
  }
  parts.push(
    `\n\n-- ============================================================\n` +
      `-- FILE: ${rel}\n` +
      `-- ============================================================\n\n` +
      body.replace(/\s*$/, '\n'),
  );
}

const OUT = resolve(SUPA, 'apply-all.sql');
writeFileSync(OUT, parts.join(''), 'utf8');
console.log(
  `db:seed OK — wrote ${relative(resolve(here, '../..'), OUT)} in enforced order ` +
    `(${ORDER.length} files; dashboard base, Discord schema, views, seeds, schema-repair).`,
);
console.log('Apply it as service_role:  psql "$DATABASE_URL" -f supabase/apply-all.sql');
