/**
 * build-apply-all.ts — emit `supabase/apply-all.sql`, the ONE ordered apply artifact (P0-C6).
 *
 * THE FOOTGUN THIS CLOSES. The per-file migrations + seeds are NOT safe to apply in filename order.
 * The whole non-linear back half depends on migration 0006 (adds `puzzles.requires_flags`) and 0007
 * (adds `puzzles.answer_kind`, which puzzles_seed.sql's second insert names) landing BEFORE the
 * seeds. metapuzzle_seed.sql / progression_seed.sql wrap their activation UPDATEs in a
 * `do $$ … if column exists … else raise exception … $$` guard: apply them before 0006 and the
 * seed batch ABORTS (the guards now fail LOUD, not silent). And if a mis-order ever slipped past,
 * `base-docket-reread-auto` — which ships active=true — would keep its default empty requires_flags
 * and LEAK its four M4 docket answers from minute one. Only a correct, enforced order is safe.
 *
 * THE ENFORCEMENT. This script concatenates the files in the ONE correct order (below), with clear
 * FILE banners, into `supabase/apply-all.sql`. `npm run db:seed` (and the `db:apply` alias) run it;
 * the operator then applies that single generated file (or pipes it to psql / the Supabase SQL
 * editor). The order is a code artifact here, not tribal knowledge in a comment — so it cannot drift
 * from what actually gets applied, and there is no "apply the loose files in Finder order" path left.
 *
 * SCOPE. The discord lineage EXTENDS the dashboard base (dashboard/supabase/migrations 0001–0003 +
 * 0004_v_record). Those base tables (players, arc_state, solves' FK targets, event_log, …) are
 * assumed already applied on the live project — this file does not recreate them (see the discord
 * migrations' own headers). apply-all.sql is idempotent + additive end-to-end (every step is
 * `create … if not exists` / `add column if not exists` / `on conflict` upsert), so it is safe to
 * re-run; re-running is in fact the canonical way to re-seed after an authored edit.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve, relative } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
// src/db -> ../../supabase
const SUPA = resolve(here, '../../supabase');

/**
 * THE ENFORCED ORDER. Migrations first (0006 + 0007 MUST precede the seeds), then the seeds in a
 * dependency-correct sequence (puzzles_seed inserts the rows every later seed UPDATEs/references;
 * metapuzzle + progression run last as they gate the back half and depend on 0006's column), then
 * schema-repair (plugin<->DB column/index reconciliation) last. Mirrors apply-tonight.sql's proven
 * ordering and additionally pins 0003/0004/0007 which that hand-assembled snapshot omitted.
 */
const ORDER: readonly string[] = [
  // ---- migrations (0006 = requires_flags, 0007 = answer_kind — BOTH before the seeds) ----
  'migrations/0003_discord.sql',
  'migrations/0004_oracle.sql',
  'migrations/0005_threads.sql',
  'migrations/0006_requires_flags.sql',
  'migrations/0007_answer_kind.sql',
  'migrations/0008_requires_quorum.sql',
  // ---- seeds (puzzles_seed FIRST; metapuzzle + progression LAST — they gate on 0006's column) ----
  'seeds/puzzles_seed.sql',
  'seeds/seventh_seed.sql',
  'seeds/thread_tags.sql',
  'seeds/thread_cards.sql',
  'seeds/side_quests.sql',
  'seeds/hints_seed.sql',
  'seeds/metapuzzle_seed.sql',
  'seeds/progression_seed.sql',
  // ---- plugin<->DB schema reconciliation (adds columns/indexes the plugin upserts need) ----
  'schema-repair.sql',
];

const HEADER = `-- ============================================================================
-- THE OBSERVANCE — apply-all.sql  (GENERATED by \`npm run db:seed\` — do not hand-edit)
-- ============================================================================
-- Apply this ONE file (Supabase SQL editor, or: psql "$DATABASE_URL" -f apply-all.sql).
-- It is the ONLY safe apply path: the files are concatenated in the ENFORCED order below,
-- with migration 0006 (puzzles.requires_flags) and 0007 (puzzles.answer_kind) BEFORE every
-- seed. Applying the loose files in filename order instead would (a) trip the fail-loud guards
-- in metapuzzle_seed / progression_seed and abort, or — worse, if forced — (b) leave
-- base-docket-reread-auto (active=true) ungated and leak its four M4 docket answers.
--
-- Assumes the dashboard base (dashboard/supabase/migrations 0001-0003 + 0004_v_record) is
-- already applied on the live project. Idempotent + additive — safe to re-run.
--
-- Ordered contents:
${ORDER.map((p, i) => `--   ${String(i + 1).padStart(2, '0')}. ${p}`).join('\n')}
-- ============================================================================

`;

const parts: string[] = [HEADER];
for (const rel of ORDER) {
  const abs = resolve(SUPA, rel);
  let body: string;
  try {
    body = readFileSync(abs, 'utf8');
  } catch {
    console.error(`db:seed FAILED — missing required file in the apply order: ${rel}`);
    process.exit(1);
  }
  parts.push(
    `\n\n-- ============================================================\n` +
      `-- FILE: ${rel}\n` +
      `-- ============================================================\n\n` +
      body.replace(/\s*$/, '\n'),
  );
}

const OUT = resolve(SUPA, 'apply-all.sql');
writeFileSync(OUT, parts.join(''), 'utf8');
console.log(
  `db:seed OK — wrote ${relative(resolve(here, '../..'), OUT)} in enforced order ` +
    `(${ORDER.length} files; 0006 + 0007 before seeds; schema-repair last).`,
);
console.log('Apply it as service_role:  psql "$DATABASE_URL" -f supabase/apply-all.sql');
