-- FORWARD RECOVERY. Executable reapplication of the reviewed UP state after the exact rollback.
-- Apply only to the same verified disposable/development target after rollback evidence.
begin;

do $$
declare
  missing_view text;
begin
  if current_setting('server_version_num')::int < 150000 then
    raise exception 'security_invoker views require PostgreSQL 15+';
  end if;
  select required.name into missing_view
  from unnest(array[
    'v_archive','v_required_media_delivery','v_case_progress','v_heatmap',
    'v_compliance_counts','v_health','v_record'
  ]) required(name)
  where to_regclass('public.' || required.name) is null
  limit 1;
  if missing_view is not null then
    raise exception 'required public projection is missing: %', missing_view;
  end if;
  if exists (
    select 1 from pg_class c join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relkind in ('r','p') and not c.relrowsecurity
  ) then
    raise exception 'every public table must have RLS before hardening';
  end if;
  if exists (
    select 1 from pg_constraint c
    where c.conrelid = 'public.dossiers'::regclass and c.contype = 'p'
  ) then
    raise exception 'unexpected dossiers primary key; re-audit the target before applying';
  end if;
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'dossiers' and column_name = 'id'
  ) then
    raise exception 'unexpected dossiers.id; re-audit the target before applying';
  end if;
end;
$$;

create schema if not exists observance_migration;
revoke all on schema observance_migration from public, anon, authenticated;

create table observance_migration.security_hardening_v2_grants as
select grantee, table_schema, table_name, privilege_type
from information_schema.role_table_grants
where table_schema = 'public' and grantee in ('anon','authenticated');

create table observance_migration.security_hardening_v2_indexes (
  index_name text primary key,
  existed_before boolean not null
);
insert into observance_migration.security_hardening_v2_indexes(index_name, existed_before)
values
  ('idx_solves_player_fk', to_regclass('public.idx_solves_player_fk') is not null),
  ('idx_answer_attempts_player_fk', to_regclass('public.idx_answer_attempts_player_fk') is not null),
  ('idx_thread_cards_thread_fk', to_regclass('public.idx_thread_cards_thread_fk') is not null),
  ('idx_thread_quests_thread_fk', to_regclass('public.idx_thread_quests_thread_fk') is not null),
  ('idx_discord_ledger_player_fk', to_regclass('public.idx_discord_ledger_player_fk') is not null),
  ('idx_oracle_attempts_player_fk', to_regclass('public.idx_oracle_attempts_player_fk') is not null),
  ('idx_hint_events_player_fk', to_regclass('public.idx_hint_events_player_fk') is not null),
  ('idx_observations_player_fk', to_regclass('public.idx_observations_player_fk') is not null),
  ('idx_evidence_receipts_player_fk', to_regclass('public.idx_evidence_receipts_player_fk') is not null),
  ('idx_required_media_node_fk', to_regclass('public.idx_required_media_node_fk') is not null),
  ('idx_identity_link_previous_player_fk', to_regclass('public.idx_identity_link_previous_player_fk') is not null);

alter table public.dossiers add column id bigint generated by default as identity;
alter table public.dossiers add constraint dossiers_pkey primary key (id);

alter view public.v_archive set (security_invoker = true);
alter view public.v_required_media_delivery set (security_invoker = true);
alter view public.v_case_progress set (security_invoker = true);
alter view public.v_heatmap set (security_invoker = true);
alter view public.v_compliance_counts set (security_invoker = true);
alter view public.v_health set (security_invoker = true);
alter view public.v_record set (security_invoker = true);

-- The application now reads these narrow projections through a server-only service client.
-- Data API grants and RLS remain separate: browser roles receive no table or view privilege.
revoke all privileges on all tables in schema public from anon, authenticated;
revoke usage, select on all sequences in schema public from anon, authenticated;
grant select, insert, update, delete on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;

create index if not exists idx_solves_player_fk on public.solves(player_id);
create index if not exists idx_answer_attempts_player_fk on public.answer_attempts(player_id);
create index if not exists idx_thread_cards_thread_fk on public.thread_cards(thread_key);
create index if not exists idx_thread_quests_thread_fk on public.thread_quests(thread_key);
create index if not exists idx_discord_ledger_player_fk on public.discord_ledger(player_id);
create index if not exists idx_oracle_attempts_player_fk on public.oracle_attempts(player_id);
create index if not exists idx_hint_events_player_fk on public.hint_events(player_id);
create index if not exists idx_observations_player_fk on public.observations(player_id);
create index if not exists idx_evidence_receipts_player_fk on public.evidence_receipts(player_id);
create index if not exists idx_required_media_node_fk on public.required_media(node_key);
create index if not exists idx_identity_link_previous_player_fk
  on public.identity_link_challenges(previous_player_id);

do $$
begin
  if exists (
    select 1 from pg_class c join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relkind = 'v'
      and coalesce(c.reloptions, '{}') @> array['security_invoker=false']
  ) then
    raise exception 'a public SECURITY DEFINER view remains';
  end if;
  if exists (
    select 1 from information_schema.role_table_grants
    where table_schema = 'public' and grantee in ('anon','authenticated')
  ) then
    raise exception 'browser Data API grants remain after hardening';
  end if;
  if not exists (
    select 1 from pg_constraint c
    where c.conrelid = 'public.dossiers'::regclass and c.contype = 'p'
  ) then
    raise exception 'dossiers primary key was not installed';
  end if;
end;
$$;

commit;
