import type { Metadata } from "next";
import Link from "next/link";
import { Breadcrumbs, LegacyShell, OldPageTitle } from "@/components/legacy/LegacyShell";

export const metadata: Metadata = { title: "Support Center - Copperline Hosting" };

export default function SupportPage() {
  return <LegacyShell active="support"><Breadcrumbs>Support Center</Breadcrumbs><OldPageTitle sub="Preserved knowledge-base index and service notices.">Support Center</OldPageTitle><div className="old-message"><b>Support desk closed:</b> New tickets, replies, uploads, and password resets are unavailable. Linked historical tickets remain read-only.</div><div className="support-grid"><section><h2>Game Server Archive</h2><a href="#ftp">FTP access</a><a href="#backups">Backup retention</a><a href="#jars">Custom server JARs</a><a href="#packs">Resource packs</a></section><section><h2>Account Archive</h2><a href="#billing">Past-due retention</a><a href="#tickets">Historical tickets</a><Link href="/clientarea.php">Retired client area</Link><Link href="/status">Network status cache</Link></section></div><div className="support-articles"><section id="ftp"><h2>FTP access</h2><p>FTP accounts were removed with customer authentication. No preserved page can recover an account password or expose stored files.</p></section><section id="backups"><h2>Backup retention</h2><p>One rolling backup was stored separately from each active game node. Cancelled-service data was normally removed after fourteen days.</p></section><section id="jars"><h2>Custom server JARs</h2><p>Customers could select a panel image or upload a custom JAR. The archived panel can no longer start or convert servers.</p></section><section id="packs"><h2>Resource packs</h2><p>Resource-pack URLs were configured by the customer. Copperline did not retain third-party pack files after account expiration.</p></section><section id="billing"><h2>Past-due retention</h2><p>Suspended services remained in active storage for fourteen days. Directory rows could survive longer in the public cache.</p></section><section id="tickets"><h2>Historical tickets</h2><p>Ticket pages are available only when a retained account or directory record links to the original ticket number.</p></section></div></LegacyShell>;
}
