param(
  [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path,
  [string]$Date = (Get-Date -Format "yyyy-MM-dd"),
  [string]$ResourcePackUrl = "",
  [switch]$SkipBundle,
  [switch]$Force
)

$ErrorActionPreference = "Stop"

function Invoke-Step([string]$Name, [string]$ScriptPath, [string[]]$ArgsList, [switch]$AllowNotReady) {
  Write-Host ""
  Write-Host "== $Name =="
  & powershell -NoProfile -ExecutionPolicy Bypass -File $ScriptPath @ArgsList
  $exit = $LASTEXITCODE
  if ($exit -ne 0 -and -not $AllowNotReady) {
    exit $exit
  }
  return $exit
}

function Invoke-StepCapture([string]$Name, [string]$ScriptPath, [string[]]$ArgsList, [string]$OutFile, [switch]$AllowNotReady) {
  Write-Host ""
  Write-Host "== $Name =="
  $output = @(& powershell -NoProfile -ExecutionPolicy Bypass -File $ScriptPath @ArgsList 2>&1)
  $exit = $LASTEXITCODE
  foreach ($line in $output) {
    Write-Host $line
  }
  $stamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
  $lines = [System.Collections.Generic.List[string]]::new()
  $lines.Add("# Launch Blocker Report - $stamp")
  $lines.Add("")
  $lines.Add("Generated by " + (Code "tools\prepare_friend_launch.ps1") + ".")
  $lines.Add("")
  $lines.Add('```text')
  foreach ($line in $output) {
    $lines.Add([string]$line)
  }
  $lines.Add('```')
  [System.IO.File]::WriteAllLines($OutFile, $lines, [System.Text.UTF8Encoding]::new($false))
  if ($exit -ne 0 -and -not $AllowNotReady) {
    exit $exit
  }
  return $exit
}

function Resolve-UnderRepo([string]$Root, [string]$Path) {
  if ([System.IO.Path]::IsPathRooted($Path)) {
    return [System.IO.Path]::GetFullPath($Path)
  }
  return [System.IO.Path]::GetFullPath((Join-Path $Root $Path))
}

function ValueOrPending([string]$Value, [string]$Fallback) {
  if ([string]::IsNullOrWhiteSpace($Value)) {
    return $Fallback
  }
  return $Value
}

function Code([string]$Value) {
  return [string]([char]0x60) + $Value + [string]([char]0x60)
}

function FileSha1OrPending([string]$Path, [string]$Fallback) {
  if (Test-Path $Path) {
    return (Get-FileHash -LiteralPath $Path -Algorithm SHA1).Hash.ToLowerInvariant()
  }
  return $Fallback
}

function Write-ManualMediaChecklist([string]$RehearsalDir, [string]$Date) {
  $path = Join-Path $RehearsalDir "manual-media-checklist.md"
  $lines = [System.Collections.Generic.List[string]]::new()
  $lines.Add("# Manual Media Checklist - $Date")
  $lines.Add("")
  $lines.Add('Use this beside `design\MANUAL-MEDIA-PACKET.md` and `design\MANUAL-MEDIA-STAGING.md` while checking the optional media. The rule for launch is strict: hosted is not automatically live; if the hosted file or URL is absent or untested, keep the player-facing trail withheld or dormant.')
  $lines.Add("")
  $lines.Add("## Found Footage")
  $lines.Add("")
  $lines.Add("| Artifact | Ready flag | Gate context | Payload | Accepted answers | Public title | Hosted URL |")
  $lines.Add("| --- | --- | --- | --- | --- | --- | --- |")
  $lines.Add('| `clip_01_prior_base.mp4` | `media_clip_01_ready` | after Record/base anomaly; `record_received` | `ASH-13` | `ash 13`; `ash thirteen`; `kept elsewhere ash 13` | `base_check_06.mp4` | `https://youtu.be/du-qp_clP7c` |')
  $lines.Add('| `clip_02_far_water_count.mp4` | `media_clip_02_ready` | after Sella/Seventh suspicion | `WHERE THE REEDS FOLD BACK` | `where the reeds fold back`; `the reeds fold back`; `reeds fold back` | `shore_copy_unlisted.mp4` | `https://youtu.be/iKqvPMHjR74` |')
  $lines.Add('| `clip_03_black_moon_toll.mp4` | `media_clip_03_ready` | after watch-floor evidence | `STAY AWAKE` | `stay awake`; `awake`; `do not close your eyes`; `do not sleep on the black moon` | `watch_floor_9_lit.mp4` | `https://youtu.be/pSPhBYMGIRc` |')
  $lines.Add('| `clip_04_release_room_late.mp4` | `media_clip_04_ready` | after `seventh_named` | `SIX RETURN, ONE IS NOT KEPT` | `six return one is not kept`; `six return and one is not kept`; `six return one not kept` | `room_below_noaudio.mp4` | `https://youtu.be/DtZizx5QIEs` |')
  $lines.Add("")
  $lines.Add("## the-hold.zip")
  $lines.Add("")
  $lines.Add('- Dashboard path: `dashboard/public/the-hold/the-hold.zip`.')
  $lines.Add('- Public deployed URL to verify: `/the-hold/the-hold.zip`.')
  $lines.Add('- Size: `17756` bytes (command-built world; no pre-generated region files).')
  $lines.Add('- SHA1: `c85cc6509477d8b51fd06142f088a98621c8f73f`.')
  $lines.Add('- Final room handoff: host fragments I-IV + common-web ending + service digits 25569; no assembled raw server endpoint.')
  $lines.Add("- Do not plant the in-world route clue until the deployed dashboard URL works from an incognito/private browser.")
  $lines.Add("")
  $lines.Add("## Recovered Archive")
  $lines.Add("")
  $lines.Add('- Ready flag: `recovered_archive_ready`.')
  $lines.Add('- Gate context: `seventh_suspected` plus `recovered_archive_ready`.')
  $lines.Add('- Spectrogram payload: `I WAS NOT KEPT`.')
  $lines.Add('- Accepted answer: `i was not kept`.')
  $lines.Add('- Do not include `AVERYN` in this archive before the name is earned elsewhere.')
  $lines.Add("")
  $lines.Add("## Production Check")
  $lines.Add("")
  $lines.Add("- [ ] Review `design\MANUAL-MEDIA-STAGING.md` for local filenames, sizes, SHA1s, and payloads.")
  $lines.Add("- [x] YouTube videos, recovered archive contents, and spectrogram payload were operator-checked on 2026-07-08.")
  $lines.Add("- [x] Final hosted URLs, final filenames, final sizes, and final SHA1s are recorded before flipping ready flags.")
  $lines.Add("- [x] Every produced artifact has exact payload, extraction method, and gate recorded.")
  $lines.Add("- [ ] No in-world clue points to a missing video, zip, Drive folder, or spectrogram file.")
  $lines.Add("- [ ] Optional media is not the sole path through the main spine.")
  $lines.Add('- [ ] Run `tools\check_external_media_readiness.ps1` before launch.')
  [System.IO.File]::WriteAllLines($path, $lines, [System.Text.UTF8Encoding]::new($false))
  return $path
}

function Write-FriendLaunchTodo(
  [string]$Root,
  [string]$Date,
  [string]$PlacementDir,
  [string]$CaptureCsv,
  [string]$RehearsalDir,
  [string]$BlockerReport,
  [string]$ManualMediaChecklist,
  [string]$LiveServerCommandSheet,
  [string]$SupabaseApplyCard,
  [string]$ResourcePackUrl,
  [bool]$HostedPackVerified
) {
  $manifestPath = Join-Path $Root "observance-deploy-manifest.json"
  $sqlBundleRel = "discord\supabase\apply-all.sql"
  $sqlBundlePath = Join-Path $Root $sqlBundleRel
  $sqlBundleSha1 = FileSha1OrPending $sqlBundlePath "PENDING - run npm run db:seed from discord"
  $pluginJarPath = "plugin\build\libs\observance-*.jar"
  $pluginJarSha1 = "PENDING - run tools\package_launch_bundle.ps1"
  $datapackPath = "observance-datapack.zip"
  $datapackSha1 = "PENDING - run tools\package_launch_bundle.ps1"
  $resourcepackPath = "observance-resourcepack.zip"
  $resourcepackSha1 = "PENDING - run tools\package_launch_bundle.ps1"
  if (Test-Path $manifestPath) {
    $manifest = Get-Content -LiteralPath $manifestPath -Raw | ConvertFrom-Json
    if ($manifest.artifacts.pluginJar) {
      $pluginJarPath = [string]$manifest.artifacts.pluginJar.path
      $pluginJarSha1 = ValueOrPending ([string]$manifest.artifacts.pluginJar.sha1) $pluginJarSha1
    }
    if ($manifest.artifacts.datapackZip) {
      $datapackPath = [string]$manifest.artifacts.datapackZip.path
      $datapackSha1 = ValueOrPending ([string]$manifest.artifacts.datapackZip.sha1) $datapackSha1
    }
    if ($manifest.artifacts.resourcepackZip) {
      $resourcepackPath = [string]$manifest.artifacts.resourcepackZip.path
      $resourcepackSha1 = ValueOrPending ([string]$manifest.artifacts.resourcepackZip.sha1) $resourcepackSha1
    }
  }

  $hostedLine = if ([string]::IsNullOrWhiteSpace($ResourcePackUrl)) {
    "PENDING - host $resourcepackPath at a direct HTTPS .zip URL, then rerun tools\prepare_friend_launch.ps1 -ResourcePackUrl <hosted-https-zip-url>."
  } elseif ($HostedPackVerified) {
    "VERIFIED - $ResourcePackUrl"
  } else {
    "SUPPLIED BUT NOT VERIFIED - rerun tools\check_hosted_resource_pack.ps1."
  }

  $path = Join-Path $RehearsalDir "friend-launch-todo.md"
  $lines = [System.Collections.Generic.List[string]]::new()
  $lines.Add("# Friend Launch Todo - $Date")
  $lines.Add("")
  $lines.Add("This is the plain checklist for the remaining live work. Use the generated quickstart for paths and the blocker report for the current machine-readable verdict.")
  $lines.Add("")
  $lines.Add("## Exact Receipts")
  $lines.Add("")
  $lines.Add("- Supabase SQL to apply: " + (Code $sqlBundleRel))
  $lines.Add("- Supabase SQL SHA1 to record after applying: " + (Code $sqlBundleSha1))
  $lines.Add("- Supabase apply card: " + (Code $SupabaseApplyCard))
  $lines.Add("- Plugin jar to upload: " + (Code $pluginJarPath))
  $lines.Add("- Plugin jar SHA1 to record: " + (Code $pluginJarSha1))
  $lines.Add("- Datapack zip to install: " + (Code $datapackPath))
  $lines.Add("- Datapack SHA1: " + (Code $datapackSha1))
  $lines.Add("- Resource pack zip to host: " + (Code $resourcepackPath))
  $lines.Add("- Resource pack SHA1 to configure/record: " + (Code $resourcepackSha1))
  $lines.Add("- Hosted resource-pack status: " + (Code $hostedLine))
  $lines.Add("")
  $lines.Add("## Do In Order")
  $lines.Add("")
  $lines.Add("- [ ] Apply " + (Code $sqlBundleRel) + " to the live Supabase project using " + (Code $SupabaseApplyCard) + ". Do not paste loose migration files after it.")
  $lines.Add("- [ ] Record the applied SQL SHA1 " + (Code $sqlBundleSha1) + " in " + (Code (Join-Path $RehearsalDir "launch-attestations.md")) + ".")
  $lines.Add("- [ ] Upload " + (Code $pluginJarPath) + " to the Paper 1.21.11 server.")
  $lines.Add("- [ ] Install " + (Code $datapackPath) + " in the live world datapacks folder.")
  $lines.Add("- [ ] Host " + (Code $resourcepackPath) + " at a direct HTTPS .zip URL.")
  $lines.Add("- [ ] Run " + (Code "tools\prepare_friend_launch.ps1 -ResourcePackUrl <hosted-https-zip-url>") + " so config, hosted-byte verification, quickstart, blocker report, media checklist, Supabase card, command sheet, launch todo, and attestations are refreshed together.")
  $lines.Add("- [ ] Use " + (Code $PlacementDir) + " to build/proof the Deep Hold rows and place the remaining outside-Hold anchors.")
  $lines.Add("- [ ] Prove the Failed Accepting route in the generated Hold: " + (Code "no witness") + " opens the old camp, " + (Code "answers are not witness") + " starts the repair files, all six repair signs accept evidence-backed corrections, and " + (Code "witness before accepting") + " opens the final rite path.")
  $lines.Add("- [ ] Fill " + (Code $CaptureCsv) + " with Deep Hold GeneratedProof, PlaceworldReceipt for stamped rows, outside-Hold coordinates, KEEP verdicts, four proof shots, and cohesion notes.")
  $lines.Add("- [ ] Use " + (Code $LiveServerCommandSheet) + " while running the live server commands; copy receipts into launch-attestations.md.")
  $lines.Add("- [ ] Review " + (Code $ManualMediaChecklist) + ' before flipping `media_clip_01_ready`, `media_clip_02_ready`, `media_clip_03_ready`, `media_clip_04_ready`, or `recovered_archive_ready`.')
  $lines.Add("- [ ] Run the live rehearsal and fill " + (Code (Join-Path $RehearsalDir "00-notes.md")) + ", " + (Code (Join-Path $RehearsalDir "fixes.md")) + ", and " + (Code (Join-Path $RehearsalDir "launch-attestations.md")) + ".")
  $lines.Add("- [ ] Complete " + (Code "design\SESSION-ZERO.md") + " before enabling capture features.")
  $lines.Add("- [ ] Rotate any exposed Supabase service_role or Discord bot credentials before inviting players.")
  $lines.Add("- [ ] Read " + (Code $BlockerReport) + " and clear every blocker it names.")
  $lines.Add("- [ ] Run final go/no-go: " + (Code ("tools\check_launch_manual_blockers.ps1 -Launch -CaptureCsv `"$CaptureCsv`" -RehearsalPacket `"$RehearsalDir`"")) + ".")
  $lines.Add("- [ ] Launch only when the final check passes and " + (Code "launch-attestations.md") + " ends with " + (Code "decision: LAUNCH") + ".")
  [System.IO.File]::WriteAllLines($path, $lines, [System.Text.UTF8Encoding]::new($false))
  return $path
}

function Write-FriendQuickstart(
  [string]$Root,
  [string]$Date,
  [string]$PlacementDir,
  [string]$CaptureCsv,
  [string]$RehearsalDir,
  [string]$ResourcePackUrl,
  [string]$BlockerReport,
  [string]$ManualMediaChecklist,
  [string]$FriendLaunchTodo,
  [string]$LiveServerCommandSheet,
  [string]$SupabaseApplyCard,
  [bool]$HostedPackVerified
) {
  $manifestPath = Join-Path $Root "observance-deploy-manifest.json"
  $pluginJarPath = "plugin\build\libs\observance-*.jar"
  $pluginJarSha1 = "PENDING - run tools\package_launch_bundle.ps1"
  $datapackPath = "observance-datapack.zip"
  $datapackSha1 = "PENDING - run tools\package_launch_bundle.ps1"
  $resourcepackPath = "observance-resourcepack.zip"
  $resourcepackSha1 = "PENDING - run tools\package_launch_bundle.ps1"
  $minecraftTarget = "Paper 1.21.11"
  $sqlBundleRel = "discord\supabase\apply-all.sql"
  $sqlBundlePath = Join-Path $Root $sqlBundleRel
  $sqlBundleSha1 = FileSha1OrPending $sqlBundlePath "PENDING - run npm run db:seed from discord"
  $sqlBundleCount = "PENDING"
  if (Test-Path $sqlBundlePath) {
    $sqlBundleText = Get-Content -LiteralPath $sqlBundlePath -Raw
    $sqlBundleCount = [string]([regex]::Matches($sqlBundleText, "(?m)^-- FILE: ").Count)
  }

  if (Test-Path $manifestPath) {
    $manifest = Get-Content -LiteralPath $manifestPath -Raw | ConvertFrom-Json
    if ($manifest.minecraftTarget) { $minecraftTarget = [string]$manifest.minecraftTarget }
    if ($manifest.artifacts.pluginJar) {
      $pluginJarPath = [string]$manifest.artifacts.pluginJar.path
      $pluginJarSha1 = ValueOrPending ([string]$manifest.artifacts.pluginJar.sha1) $pluginJarSha1
    }
    if ($manifest.artifacts.datapackZip) {
      $datapackPath = [string]$manifest.artifacts.datapackZip.path
      $datapackSha1 = ValueOrPending ([string]$manifest.artifacts.datapackZip.sha1) $datapackSha1
    }
    if ($manifest.artifacts.resourcepackZip) {
      $resourcepackPath = [string]$manifest.artifacts.resourcepackZip.path
      $resourcepackSha1 = ValueOrPending ([string]$manifest.artifacts.resourcepackZip.sha1) $resourcepackSha1
    }
  }

  $quickstartPath = Join-Path $RehearsalDir "friend-launch-quickstart.md"
  $resourcePackLine = if ([string]::IsNullOrWhiteSpace($ResourcePackUrl)) {
    "PENDING - host $resourcepackPath at an HTTPS .zip URL, then rerun this helper with -ResourcePackUrl <hosted-https-zip-url>."
  } else {
    $ResourcePackUrl
  }
  $hostedPackVerification = if ($HostedPackVerified) {
    "VERIFIED - tools\check_hosted_resource_pack.ps1 downloaded the hosted zip and matched SHA1 before this quickstart was written."
  } else {
    "PENDING - no hosted URL was supplied to this helper."
  }

  $lines = [System.Collections.Generic.List[string]]::new()
  $lines.Add("# Friend Launch Quickstart - $Date")
  $lines.Add("")
  $lines.Add("Use this file as the handoff for the exact packet generated by " + (Code "tools\prepare_friend_launch.ps1") + ".")
  $lines.Add("")
  $lines.Add("## Generated Paths")
  $lines.Add("")
  $lines.Add("- Deploy manifest: " + (Code "observance-deploy-manifest.json"))
  $lines.Add("- Placement packet: " + (Code $PlacementDir))
  $lines.Add("- Coordinate capture CSV: " + (Code $CaptureCsv))
  $lines.Add("- Rehearsal packet: " + (Code $RehearsalDir))
  $lines.Add("- Rehearsal notes: " + (Code (Join-Path $RehearsalDir "00-notes.md")))
  $lines.Add("- Launch attestations: " + (Code (Join-Path $RehearsalDir "launch-attestations.md")))
  $lines.Add("- Current blocker report: " + (Code $BlockerReport))
  $lines.Add("- Manual media checklist: " + (Code $ManualMediaChecklist))
  $lines.Add("- Friend launch todo: " + (Code $FriendLaunchTodo))
  $lines.Add("- Live server command sheet: " + (Code $LiveServerCommandSheet))
  $lines.Add("- Supabase apply card: " + (Code $SupabaseApplyCard))
  $lines.Add("")
  $lines.Add("## Exact Supabase SQL")
  $lines.Add("")
  $lines.Add("- Apply path: " + (Code $sqlBundleRel))
  $lines.Add("- Apply-all SHA1: " + (Code $sqlBundleSha1))
  $lines.Add("- Ordered bundle files: " + (Code $sqlBundleCount))
  $lines.Add("- Rule: apply this one generated file only; do not paste loose migrations after it.")
  $lines.Add("")
  $lines.Add("## Exact Build Artifacts")
  $lines.Add("")
  $lines.Add("- Minecraft target: " + (Code $minecraftTarget))
  $lines.Add("- Plugin jar: " + (Code $pluginJarPath))
  $lines.Add("- Plugin jar SHA1: " + (Code $pluginJarSha1))
  $lines.Add("- Datapack zip: " + (Code $datapackPath))
  $lines.Add("- Datapack SHA1: " + (Code $datapackSha1))
  $lines.Add("- Resource pack zip: " + (Code $resourcepackPath))
  $lines.Add("- Resource pack SHA1: " + (Code $resourcepackSha1))
  $lines.Add("- Hosted resource-pack URL: " + (Code $resourcePackLine))
  $lines.Add("- Hosted resource-pack verification: " + (Code $hostedPackVerification))
  $lines.Add("")
  $lines.Add("## Live Setup Order")
  $lines.Add("")
  $lines.Add("1. Apply " + (Code $sqlBundleRel) + " to the live Supabase project using " + (Code $SupabaseApplyCard) + " and record SHA1 " + (Code $sqlBundleSha1) + ".")
  $lines.Add("2. Upload the plugin jar above to the Paper server.")
  $lines.Add("3. Install the datapack zip above in the world datapacks folder.")
  $lines.Add("4. Host the resource pack zip above at the hosted URL listed here.")
  $lines.Add("5. If the hosted URL is still pending, rerun " + (Code "tools\prepare_friend_launch.ps1 -ResourcePackUrl <hosted-https-zip-url>") + ".")
  $lines.Add("6. Verify hosted pack bytes with " + (Code "tools\check_hosted_resource_pack.ps1") + ".")
  $lines.Add("7. Run " + (Code "/obs placehold build") + "/" + (Code "/obs placehold audit") + " for Hold-owned rows. For outside-Hold rows, " + (Code "/obs site set") + " surveys the anchor and " + (Code "/obs placeworld") + " stamps any placeworld/dimension set-piece before it counts.")
  $lines.Add("8. Prove the Failed Accepting route: " + (Code "case_board") + "/" + (Code "no witness") + " gates the old camp, " + (Code "prior_camp") + "/" + (Code "answers are not witness") + " starts six repair files, all six repair signs are evidence-backed, and " + (Code "failed_accepting") + "/" + (Code "witness before accepting") + " is required before " + (Code "rite-tokens") + ".")
  $lines.Add("9. Stamp " + (Code "nether_forge") + " from the Nether and " + (Code "end_seventh_shrine") + " from the End; record the " + (Code "nether_forge_placed") + " and " + (Code "end_seventh_shrine_placed") + " receipts.")
  $lines.Add("10. Fill " + (Code "coords-capture.csv") + " with GeneratedProof, PlaceworldReceipt, coordinates, KEEP verdicts, four proof shots, and cohesion notes.")
  $lines.Add("11. Run the live rehearsal and fill " + (Code "00-notes.md") + ", " + (Code "launch-attestations.md") + ", and " + (Code "fixes.md") + ".")
  $lines.Add("12. Use " + (Code $LiveServerCommandSheet) + " for exact live command receipts.")
  $lines.Add("13. Review " + (Code $ManualMediaChecklist) + " before flipping any media-ready flags.")
  $lines.Add("14. Work through " + (Code $FriendLaunchTodo) + " as the plain launch checklist.")
  $lines.Add("15. Read " + (Code $BlockerReport) + " and move anything actionable into the rehearsal fixes list.")
  $lines.Add("16. Complete session zero and credential rotation before inviting players.")
  $lines.Add("17. Run the final go/no-go command below.")
  $lines.Add("")
  $lines.Add("## Final Go/No-Go")
  $lines.Add("")
  $lines.Add('```powershell')
  $lines.Add('powershell -NoProfile -ExecutionPolicy Bypass -File tools\check_launch_manual_blockers.ps1 -Launch -CaptureCsv "' + $CaptureCsv + '" -RehearsalPacket "' + $RehearsalDir + '"')
  $lines.Add('```')
  $lines.Add("")
  $lines.Add("Launch only when that command passes and " + (Code "launch-attestations.md") + " ends with " + (Code "decision: LAUNCH") + ".")

  [System.IO.File]::WriteAllLines($quickstartPath, $lines, [System.Text.UTF8Encoding]::new($false))
  return $quickstartPath
}

$repoFull = [System.IO.Path]::GetFullPath($RepoRoot)
$tools = Join-Path $repoFull "tools"
$placementRoot = Join-Path $repoFull "build\launch-placement"
$placementDir = Join-Path $placementRoot $Date
$captureCsv = Join-Path $placementDir "coords-capture.csv"
$rehearsalDir = Join-Path (Join-Path $repoFull "rehearsals") $Date
$blockerReport = Join-Path $rehearsalDir "launch-blockers.md"
$manualMediaChecklist = Join-Path $rehearsalDir "manual-media-checklist.md"
$friendLaunchTodo = Join-Path $rehearsalDir "friend-launch-todo.md"
$liveServerCommandSheet = Join-Path $rehearsalDir "live-server-command-sheet.md"
$supabaseApplyCard = Join-Path $rehearsalDir "supabase-apply-card.md"

foreach ($script in @(
  "package_launch_bundle.ps1",
  "check_deploy_manifest.ps1",
  "set_resource_pack_config.ps1",
  "check_hosted_resource_pack.ps1",
  "new_launch_placement_packet.ps1",
  "new_rehearsal_packet.ps1",
  "check_launch_manual_blockers.ps1"
)) {
  $path = Join-Path $tools $script
  if (-not (Test-Path $path)) {
    throw "friend launch prep: missing required tool: $path"
  }
}

$applyAllSql = Join-Path $repoFull "discord\supabase\apply-all.sql"
if (-not (Test-Path $applyAllSql)) {
  throw "friend launch prep: missing generated Supabase SQL bundle: $applyAllSql"
}

if (-not $SkipBundle) {
  Invoke-Step "Build deploy bundle" (Join-Path $tools "package_launch_bundle.ps1") @("-RepoRoot", $repoFull) | Out-Null
} else {
  Write-Host "Skipping deploy bundle build. Verifying current deploy manifest before using existing jars/zips."
  Invoke-Step "Verify existing deploy bundle" (Join-Path $tools "check_deploy_manifest.ps1") @("-RepoRoot", $repoFull)
}

if (-not [string]::IsNullOrWhiteSpace($ResourcePackUrl)) {
  Invoke-Step "Set hosted resource-pack URL/SHA1" (Join-Path $tools "set_resource_pack_config.ps1") @(
    "-RepoRoot", $repoFull,
    "-Url", $ResourcePackUrl
  ) | Out-Null
  Invoke-Step "Verify hosted resource-pack bytes" (Join-Path $tools "check_hosted_resource_pack.ps1") @(
    "-RepoRoot", $repoFull,
    "-Url", $ResourcePackUrl
  ) | Out-Null
}

$placementArgs = @("-RepoRoot", $repoFull, "-OutRoot", $placementRoot, "-Date", $Date)
if ($Force) { $placementArgs += "-Force" }
Invoke-Step "Create launch placement packet" (Join-Path $tools "new_launch_placement_packet.ps1") $placementArgs | Out-Null

$rehearsalArgs = @("-RepoRoot", $repoFull, "-OutRoot", "rehearsals", "-Date", $Date)
if ($Force) { $rehearsalArgs += "-Force" }
Invoke-Step "Create live rehearsal packet" (Join-Path $tools "new_rehearsal_packet.ps1") $rehearsalArgs | Out-Null

$blockerArgs = @(
  "-RepoRoot", $repoFull,
  "-Launch",
  "-CaptureCsv", (Resolve-UnderRepo $repoFull $captureCsv),
  "-RehearsalPacket", (Resolve-UnderRepo $repoFull $rehearsalDir)
)
Invoke-StepCapture "Current launch blockers" (Join-Path $tools "check_launch_manual_blockers.ps1") $blockerArgs $blockerReport -AllowNotReady | Out-Null
$hostedPackVerified = -not [string]::IsNullOrWhiteSpace($ResourcePackUrl)
$manualMediaChecklist = Write-ManualMediaChecklist $rehearsalDir $Date
if (-not (Test-Path -LiteralPath $liveServerCommandSheet)) {
  throw "friend launch prep: rehearsal packet did not create expected command sheet: $liveServerCommandSheet"
}
if (-not (Test-Path -LiteralPath $supabaseApplyCard)) {
  throw "friend launch prep: rehearsal packet did not create expected Supabase apply card: $supabaseApplyCard"
}
$friendLaunchTodo = Write-FriendLaunchTodo $repoFull $Date $placementDir $captureCsv $rehearsalDir $blockerReport $manualMediaChecklist $liveServerCommandSheet $supabaseApplyCard $ResourcePackUrl $hostedPackVerified
$quickstartPath = Write-FriendQuickstart $repoFull $Date $placementDir $captureCsv $rehearsalDir $ResourcePackUrl $blockerReport $manualMediaChecklist $friendLaunchTodo $liveServerCommandSheet $supabaseApplyCard $hostedPackVerified

Write-Host ""
Write-Host "friend launch prep packet ready:"
Write-Host "  deploy manifest:    observance-deploy-manifest.json"
Write-Host "  supabase SQL:       discord\supabase\apply-all.sql"
Write-Host "  supabase SQL sha1:  $((Get-FileHash -LiteralPath $applyAllSql -Algorithm SHA1).Hash.ToLowerInvariant())"
Write-Host "  placement packet:   $placementDir"
Write-Host "  coordinate capture: $captureCsv"
Write-Host "  rehearsal packet:   $rehearsalDir"
Write-Host "  quickstart:         $quickstartPath"
Write-Host "  blocker report:     $blockerReport"
Write-Host "  media checklist:    $manualMediaChecklist"
Write-Host "  launch todo:        $friendLaunchTodo"
Write-Host "  command sheet:      $liveServerCommandSheet"
Write-Host "  supabase card:      $supabaseApplyCard"
if (-not [string]::IsNullOrWhiteSpace($ResourcePackUrl)) {
  Write-Host "  resource-pack URL:  $ResourcePackUrl"
}
Write-Host ""
Write-Host "next live steps:"
Write-Host "  1) Apply discord\supabase\apply-all.sql to the live Supabase project."
Write-Host "  2) Upload plugin/build/libs/observance-*.jar to the Paper server."
Write-Host "  3) Install observance-datapack.zip in the world datapacks folder."
if ([string]::IsNullOrWhiteSpace($ResourcePackUrl)) {
  Write-Host "  4) Host observance-resourcepack.zip at an HTTPS .zip URL."
  Write-Host "  5) Rerun this helper with -ResourcePackUrl <hosted-https-zip-url>, or run tools\set_resource_pack_config.ps1 -Url <hosted-https-zip-url>."
  Write-Host "  6) Run tools\check_hosted_resource_pack.ps1 after the URL/SHA1 are configured."
  Write-Host "  7) Build/proof the Deep Hold rows; use /obs site set only as survey, then /obs placeworld to stamp placeworld/dimension rows."
  Write-Host "  8) Prove the Failed Accepting route and its old-camp physical gate before rite-tokens."
  Write-Host "  9) Stamp nether_forge in the Nether and end_seventh_shrine in the End; record their placement flag receipts."
  Write-Host "  10) Fill coords-capture.csv with GeneratedProof, PlaceworldReceipt, coordinates, KEEP verdicts, four proof shots, and cohesion notes."
  Write-Host "  11) Run the live rehearsal and fill launch-attestations.md."
  Write-Host "  12) Rerun tools\check_launch_manual_blockers.ps1 -Launch -CaptureCsv `"$captureCsv`" -RehearsalPacket `"$rehearsalDir`"."
} else {
  Write-Host "  4) Hosted URL/SHA1 is already verified and written to plugin config."
  Write-Host "  5) Keep observance-resourcepack.zip at that exact URL; rerun tools\check_hosted_resource_pack.ps1 if the host changes."
  Write-Host "  6) Build/proof the Deep Hold rows; use /obs site set only as survey, then /obs placeworld to stamp placeworld/dimension rows."
  Write-Host "  7) Prove the Failed Accepting route and its old-camp physical gate before rite-tokens."
  Write-Host "  8) Stamp nether_forge in the Nether and end_seventh_shrine in the End; record their placement flag receipts."
  Write-Host "  9) Fill coords-capture.csv with GeneratedProof, PlaceworldReceipt, coordinates, KEEP verdicts, four proof shots, and cohesion notes."
  Write-Host "  10) Run the live rehearsal and fill launch-attestations.md."
  Write-Host "  11) Rerun tools\check_launch_manual_blockers.ps1 -Launch -CaptureCsv `"$captureCsv`" -RehearsalPacket `"$rehearsalDir`"."
}
