param(
  [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path,
  [string]$Date = (Get-Date -Format "yyyy-MM-dd"),
  [string]$ResourcePackUrl = "",
  [switch]$SkipBundle,
  [switch]$Force
)

$ErrorActionPreference = "Stop"

function Code([string]$Value) {
  return [string]([char]0x60) + $Value + [string]([char]0x60)
}

function Write-ServerTestGuide(
  [string]$Root,
  [string]$Date,
  [string]$PlacementDir,
  [string]$CaptureCsv,
  [string]$RehearsalDir,
  [string]$ResourcePackUrl,
  [bool]$SkipBundle
) {
  $guidePath = Join-Path $RehearsalDir "server-test-guide.md"
  $manifestPath = Join-Path $Root "observance-deploy-manifest.json"
  $applyAllPath = Join-Path $Root "discord\supabase\apply-all.sql"
  $applyAllSha1 = if (Test-Path $applyAllPath) { (Get-FileHash -LiteralPath $applyAllPath -Algorithm SHA1).Hash.ToLowerInvariant() } else { "PENDING - missing discord\supabase\apply-all.sql" }
  $resourcePackStatus = if ([string]::IsNullOrWhiteSpace($ResourcePackUrl)) {
    "not supplied; host the resource pack and rerun this helper with -ResourcePackUrl before any player-facing pack test"
  } else {
    $ResourcePackUrl
  }

  $artifactLines = [System.Collections.Generic.List[string]]::new()
  if (Test-Path $manifestPath) {
    $manifest = Get-Content -LiteralPath $manifestPath -Raw | ConvertFrom-Json
    if ($manifest.minecraftTarget) { $artifactLines.Add("- Minecraft target: " + (Code ([string]$manifest.minecraftTarget))) }
    if ($manifest.artifacts.pluginJar) { $artifactLines.Add("- Plugin jar: " + (Code ([string]$manifest.artifacts.pluginJar.path)) + " / SHA1 " + (Code ([string]$manifest.artifacts.pluginJar.sha1))) }
    if ($manifest.artifacts.datapackZip) { $artifactLines.Add("- Datapack zip: " + (Code ([string]$manifest.artifacts.datapackZip.path)) + " / SHA1 " + (Code ([string]$manifest.artifacts.datapackZip.sha1))) }
    if ($manifest.artifacts.resourcepackZip) { $artifactLines.Add("- Resource pack zip: " + (Code ([string]$manifest.artifacts.resourcepackZip.path)) + " / SHA1 " + (Code ([string]$manifest.artifacts.resourcepackZip.sha1))) }
  }
  if ($artifactLines.Count -eq 0) {
    $artifactLines.Add("- PENDING - run " + (Code "tools\package_launch_bundle.ps1") + " or rerun this helper without " + (Code "-SkipBundle") + ".")
  }

  $buildMode = if ($SkipBundle) {
    "fast prep: existing deploy manifest was verified; rebuild before uploading fresh bytes"
  } else {
    "full prep: deploy bundle was rebuilt before this guide was written"
  }

  $lines = [System.Collections.Generic.List[string]]::new()
  $lines.Add("# Server Test Guide - $Date")
  $lines.Add("")
  $lines.Add("Generated by " + (Code "tools\prepare_server_test.ps1") + ". This is the practical server-test handoff; it points to the deeper launch placement and rehearsal packets instead of replacing them.")
  $lines.Add("")
  $lines.Add("## Test Depths")
  $lines.Add("")
  $lines.Add("Use the shallowest depth that answers today's question. Do not blur these verdicts together.")
  $lines.Add("")
  $lines.Add("| Depth | Goal | Allowed shortcuts | Must prove | Verdict label |")
  $lines.Add("| --- | --- | --- | --- | --- |")
  $lines.Add("| Smoke test | Server boots and the core wiring is alive. | Operator present, compact world, temporary coordinates, media flags withheld. | Plugin loads, datapack enabled, resource pack offered/loaded, Supabase writes work, one answer sign resolves, Wren/townsfolk can spawn, Unlit commands do not error. | `TECHNICAL-SMOKE-PASS` only. |")
  $lines.Add("| Vertical slice | A veteran group can understand one real path without operator explanation. | 8-12 curated anchors instead of all 67; one keeper, two side proofs, one Unlit house, one web/Discord touch. | Discovery, answer formatting, NPC/world proof, side-lore value, Record/dashboard handoff, one scare, one delayed callback. | `PLAYABLE-SLICE-PASS` only. |")
  $lines.Add("| Full rehearsal | The whole ARG can be run by friends before launch. | None that affect players; operators may observe and record. | All 67 launch proof rows (Hold-generated plus outside-Hold anchors), all keeper theories, all eight Unlit houses, all media readiness decisions, finale/release, proof shots and clips. | `SERVER-TEST-READY` or `DO-NOT-TEST`. |")
  $lines.Add("| Launch go/no-go | Final invitation decision. | None. | Completed launch attestations, real proof assets, no missing outside-Hold coordinates, no missing Deep Hold GeneratedProof, no missing media, session-zero consent, credential rotation. | `LAUNCH` or `DO NOT LAUNCH`. |")
  $lines.Add("")
  $lines.Add("## Generated Packet Paths")
  $lines.Add("")
  $lines.Add("- Build mode: " + (Code $buildMode))
  $lines.Add("- Placement packet: " + (Code $PlacementDir))
  $lines.Add("- Coordinate capture CSV: " + (Code $CaptureCsv))
  $lines.Add("- Rehearsal packet: " + (Code $RehearsalDir))
  $lines.Add("- Friend quickstart: " + (Code (Join-Path $RehearsalDir "friend-launch-quickstart.md")))
  $lines.Add("- Current blocker report: " + (Code (Join-Path $RehearsalDir "launch-blockers.md")))
  $lines.Add("- Live command sheet: " + (Code (Join-Path $RehearsalDir "live-server-command-sheet.md")))
  $lines.Add("- Supabase apply card: " + (Code (Join-Path $RehearsalDir "supabase-apply-card.md")))
  $lines.Add("- Manual media checklist: " + (Code (Join-Path $RehearsalDir "manual-media-checklist.md")))
  $lines.Add("- Test notes to fill: " + (Code (Join-Path $RehearsalDir "00-notes.md")))
  $lines.Add("- Fix list to fill: " + (Code (Join-Path $RehearsalDir "fixes.md")))
  $lines.Add("- Attestations to fill for full rehearsal/launch: " + (Code (Join-Path $RehearsalDir "launch-attestations.md")))
  $lines.Add("")
  $lines.Add("## Exact Artifacts")
  $lines.Add("")
  foreach ($artifactLine in $artifactLines) { $lines.Add($artifactLine) }
  $lines.Add("- Supabase SQL bundle: " + (Code "discord\supabase\apply-all.sql") + " / SHA1 " + (Code $applyAllSha1))
  $lines.Add("- Hosted resource-pack URL: " + (Code $resourcePackStatus))
  $lines.Add("")
  $lines.Add("## Before Touching The Server")
  $lines.Add("")
  $lines.Add("1. Decide the test depth and write it at the top of " + (Code (Join-Path $RehearsalDir "00-notes.md")) + ".")
  $lines.Add("2. Run repo checks relevant to your changes. Minimum before any server test:")
  $lines.Add("")
  $lines.Add('```powershell')
  $lines.Add("python tools\check_experience_coherence.py")
  $lines.Add("powershell -NoProfile -ExecutionPolicy Bypass -File tools\check_minecraft_text_surfaces.ps1")
  $lines.Add("powershell -NoProfile -ExecutionPolicy Bypass -File tools\check_operator_docs.ps1")
  $lines.Add("powershell -NoProfile -ExecutionPolicy Bypass -File tools\check_friend_launch_prep.ps1")
  $lines.Add("powershell -NoProfile -ExecutionPolicy Bypass -File tools\check_server_test_prep.ps1")
  $lines.Add('```')
  $lines.Add("")
  $lines.Add("3. If Java, datapack, resource pack, or config changed, rebuild the deploy bundle:")
  $lines.Add("")
  $lines.Add('```powershell')
  $lines.Add("powershell -NoProfile -ExecutionPolicy Bypass -File tools\package_launch_bundle.ps1")
  $lines.Add('```')
  $lines.Add("")
  $lines.Add("4. If database seeds or migrations changed, regenerate and apply only the bundled SQL:")
  $lines.Add("")
  $lines.Add('```powershell')
  $lines.Add("Push-Location discord")
  $lines.Add("npm run db:seed")
  $lines.Add("npm run audit")
  $lines.Add("Pop-Location")
  $lines.Add('```')
  $lines.Add("")
  $lines.Add("5. Apply " + (Code "discord\supabase\apply-all.sql") + " in Supabase SQL Editor. Record SHA1 " + (Code $applyAllSha1) + " in " + (Code "launch-attestations.md") + ". Do not paste loose migration or seed files afterward.")
  $lines.Add("6. Host " + (Code "observance-resourcepack.zip") + " at a direct HTTPS .zip URL. Then rerun:")
  $lines.Add("")
  $lines.Add('```powershell')
  $lines.Add("powershell -NoProfile -ExecutionPolicy Bypass -File tools\prepare_server_test.ps1 -ResourcePackUrl <hosted-https-zip-url> -Force")
  $lines.Add("powershell -NoProfile -ExecutionPolicy Bypass -File tools\check_hosted_resource_pack.ps1")
  $lines.Add('```')
  $lines.Add("")
  $lines.Add("## Server Install Checklist")
  $lines.Add("")
  $lines.Add("- [ ] Paper 1.21.11 server is created with Java 21 and enough memory for the test group.")
  $lines.Add("- [ ] Upload the plugin jar from the manifest into " + (Code "plugins/") + ".")
  $lines.Add("- [ ] Set " + (Code "plugins/Observance/config.yml") + " Supabase " + (Code "service-key") + " to the live service_role secret.")
  $lines.Add("- [ ] Install the datapack zip/folder into the world's " + (Code "datapacks/") + " folder and run " + (Code "/datapack list") + ".")
  $lines.Add("- [ ] Configure the hosted resource-pack URL/SHA1 with " + (Code "tools\set_resource_pack_config.ps1") + " or this helper's " + (Code "-ResourcePackUrl") + ".")
  $lines.Add("- [ ] Restart the server after plugin/config changes; use " + (Code "/reload") + " only for datapack/resource-only checks.")
  $lines.Add("- [ ] Op the operator account before any test commands.")
  $lines.Add("")
  $lines.Add("## Smoke Test Script")
  $lines.Add("")
  $lines.Add("Run this with one operator account and, ideally, one non-op account. It should take 30-60 minutes.")
  $lines.Add("")
  $lines.Add("1. Join with the resource pack enabled. Screenshot pack prompt and one custom rune/font surface.")
  $lines.Add("2. In console or in game, run:")
  $lines.Add("")
  $lines.Add('```text')
  $lines.Add("/observance status")
  $lines.Add("/observance preflight")
  $lines.Add("/observance visualaudit")
  $lines.Add("/observance dialogueaudit")
  $lines.Add('```')
  $lines.Add("")
  $lines.Add("3. Required status receipt: " + (Code "supabase configured: true") + ", " + (Code "last db call ok: true") + ", " + (Code "queued writes: 0") + ".")
  $lines.Add("4. Stage the production Deep Hold or, separately, a compact rehearsal board:")
  $lines.Add("")
  $lines.Add('```text')
  $lines.Add("/observance placehold build")
  $lines.Add("/observance placehold audit")
  $lines.Add("/observance placehold sync")
  $lines.Add("# rehearsal board only, not production setup:")
  $lines.Add("/observance prepworld")
  $lines.Add("/observance townsfolk spawn")
  $lines.Add("/observance wren spawn")
  $lines.Add('```')
  $lines.Add("")
  $lines.Add("5. " + (Code "/observance placehold build [depth]") + " carves the production Deep Hold from the player's surface mouth (default depth 392; accepted range 340-520). It builds a broad protected stair descent, places the main Hold well below/farther south of the run point, and arranges functional fixtures through one encased civic ruin: Return Mouth, grand Keeper Court, upper terraces, archive/gallery, market/collapse wing, Lamp-works descent, threshold floor, and side hush. From console use " + (Code "/observance placehold build <world> <x> <y> <z>") + " where x/y/z is the underground court anchor. It should report 64/64 hold sites, 7/7 full-width gates, records 8/8, entry walkable, protected Hold/entry-stair regions, grand-court/terrace/early-route/enclosure audit clean, and zero critical findings. The surface prologue sites are placed separately with " + (Code "/observance placeprologue") + ".")
  $lines.Add("5a. Walk the Return Mouth stair as a normal player: it must start where the command was run, descend without ladders, stay encased in intentional stone, reach the main Return Mouth without a dead end, and not expose vanilla caves, fluids, or surface terrain inside the Hold.")
  $lines.Add("5b. For every open gate, walk seven-player-width traffic through it without jumping or single-file squeezing. For every sealed gate, try the ugly routes too: wall edges, ceiling, side galleries, fixture tops, and dread side path. A sealed gate must block the whole passable section, not just show bars in the center.")
  $lines.Add("5c. Treat " + (Code "/observance placehold audit") + " as failed unless it prints " + (Code "records:    8/8") + " and " + (Code "entry:      walkable") + " with zero critical findings. The audit now samples the lower-landing-to-court early route, Keeper Court approaches, grand-court floor, upper terraces, sealed-gate ugly routes, controlled geology, covered-copy record, and district books for launch-critical fragments such as " + (Code "One row stayed blank") + ", " + (Code "Do not break the wall") + ", " + (Code "Plate. Name. Word.") + ", and " + (Code "uncrossed word") + "; if any fragment, route sample, or civic-shell sample is missing, rebuild the Hold before playtest.")
  $lines.Add("6. The default prepworld board uses 36-block spacing. Use it only for rehearsal; old overlapping rehearsal boards should be abandoned, not reused.")
  $lines.Add("7. Trigger the prologue as a player, not just with an admin flag: read the report lectern or sneak-right-click near the rune rosetta/reckoning stone.")
  $lines.Add("8. Inspect the Rosetta as a normal player: the lectern must contain the " + (Code "the rosetta") + " book, the rune/plaintext crib signs must render with the resource pack, and refusing the resource pack must be obvious enough to fail the smoke test.")
  $lines.Add("9. Inspect Mara and the side-proof rooms: every lectern must hold a book, ordinary barrels/chests should contain local ledgers/receipts/witness notes, decorative chiseled bookshelves are visibly occupied, and mechanic-owned shelves are not randomly pre-filled.")
  $lines.Add("10. Inspect Orin's crouch/banner site: standing should feel blocked or awkward at the lintel, sneaking should pass, the low BOW/STONE signs should be readable while stooped, and all six wall banners must render on masonry backing instead of floating or replacing the wall.")
  $lines.Add("11. Look across the Hold, rehearsal board, and any manually placed site: there should be no beacon beams. If a site is only findable by operator knowledge or a sky marker, mark placement/clueing as failed.")
  $lines.Add("12. Submit one answer on a blank answer sign. Confirm the sign clears, feedback is understandable, and the next clue appears without operator explanation.")
  $lines.Add("12a. For that same puzzle, run the leave-and-return loop: reach the puzzle, realize more evidence is needed, leave by an authored route, find the missing clue, return without teleport/operator handholding, and submit the answer. If leaving unloads the route, loses the answer surface, consumes a one-use item, strands a player behind a gate, or makes the input location unclear, the slice fails.")
  $lines.Add("12b. If the test touches late-game content, prove the Failed Accepting chain as a normal player: " + (Code "case_board") + " -> " + (Code "no witness") + ", sealed prior gate opens, " + (Code "prior_camp") + " -> " + (Code "answers are not witness") + ", six keeper repair files, then " + (Code "failed_accepting") + " -> " + (Code "witness before accepting") + ". " + (Code "rite-tokens") + " must stay closed until " + (Code "prior_witness_ready") + ".")
  $lines.Add("13. Talk to Wren and at least two townsfolk. Write down any line that sounds like a quest marker, a joke, fantasy fog, or a contradiction.")
  $lines.Add("14. Run a minimal Unlit command health check:")
  $lines.Add("")
  $lines.Add('```text')
  $lines.Add("/obs unlit audit")
  $lines.Add("/obs unlit pass light")
  $lines.Add("/obs unlit pass house")
  $lines.Add('```')
  $lines.Add("")
  $lines.Add("15. Open the dashboard/Record from a normal browser and an incognito/private browser. Confirm player-facing pages do not expose admin setup text, raw endpoints, or missing media.")
  $lines.Add("16. Smoke pass only means the machine works. It does not mean the ARG is good or launch-ready.")
  $lines.Add("")
  $lines.Add("## Vertical Slice Test Script")
  $lines.Add("")
  $lines.Add("Use this before inviting the full group. It should take 3-5 hours with two or three players.")
  $lines.Add("")
  $lines.Add("1. Pick one keeper lane, two side-lore lanes, one NPC callback, one custom mechanic, one web/Discord touch, and one Unlit house.")
  $lines.Add("2. Place only the anchors needed for that slice, but place them like final content: believable terrain, approach route, readable focal object, answer/action space, and exit route.")
  $lines.Add("3. For every placed anchor, capture approach/focal/action/exit screenshots and note why a player would go there.")
  $lines.Add("4. Players should learn how to submit answers from the world itself. If someone asks the operator what format to type or where to type it, mark it as a fail and improve the clue, nearby unwaxed filing sign, feedback, or route framing.")
  $lines.Add("4a. At least one tested puzzle must require backtracking for evidence: players should be able to leave the puzzle, gather the missing clue, and come back later with the world still readable, gated correctly, and solvable.")
  $lines.Add("5. The side lore must change a theory. If it only says spooky background, cut it, move it, or make it evidence.")
  $lines.Add("6. Test one delayed callback: a thing learned in Minecraft should matter later in Record, Discord, an NPC line, Unlit, or finale eligibility.")
  $lines.Add("7. Test one failure path: wrong sign answer, wrong object interaction, missing group member, dark/Unlit cheese attempt, and resource-pack refusal.")
  $lines.Add("8. Fill the " + (Code "Puzzle Fairness Matrix") + ", " + (Code "Side Path Value Matrix") + ", and " + (Code "First-Hour Pacing") + " sections in " + (Code "00-notes.md") + ".")
  $lines.Add("9. Vertical slice passes only if players can state: what happened, why it matters, where they want to go next, and what evidence changed their belief.")
  $lines.Add("")
  $lines.Add("## Full Rehearsal Script")
  $lines.Add("")
  $lines.Add("Run this before a real launch invitation. Expect multiple sessions.")
  $lines.Add("")
  $lines.Add("1. Generate or reuse the placement packet and work lane by lane:")
  $lines.Add("")
  $lines.Add('```text')
  $lines.Add("/observance site todo")
  $lines.Add("/observance site plan lanes")
  $lines.Add("/observance site next <lane>")
  $lines.Add("/observance site plan <siteId>")
  $lines.Add("/observance site set <siteId>")
  $lines.Add('```')
  $lines.Add("")
  $lines.Add("2. Fill " + (Code "coords-capture.csv") + " with GeneratedProof for Deep Hold rows, ChosenWorld/X/Y/Z for outside-Hold rows, SurveyedBy, VisualStatus, proof shot filenames, and cohesion notes.")
  $lines.Add("3. During placement, run:")
  $lines.Add("")
  $lines.Add('```powershell')
  $lines.Add("powershell -NoProfile -ExecutionPolicy Bypass -File tools\check_launch_coord_quality.ps1 -CaptureCsv `"" + $CaptureCsv + "`"")
  $lines.Add('```')
  $lines.Add("")
  $lines.Add("4. For final rehearsal, run the launch-strength coordinate gate:")
  $lines.Add("")
  $lines.Add('```powershell')
  $lines.Add("powershell -NoProfile -ExecutionPolicy Bypass -File tools\check_launch_coord_quality.ps1 -Launch -CaptureCsv `"" + $CaptureCsv + "`"")
  $lines.Add('```')
  $lines.Add("")
  $lines.Add("5. Build Unlit as a real mirrored expedition, not a command demo:")
  $lines.Add("")
  $lines.Add('```text')
  $lines.Add("/obs unlit site entry")
  $lines.Add("/obs unlit site spawn")
  $lines.Add("/obs unlit site exit")
  $lines.Add("/obs unlit buildmode off")
  $lines.Add("/obs unlit darken all 138")
  $lines.Add("/obs unlit border 138")
  $lines.Add("/obs unlit audit")
  $lines.Add("/obs unlit ready")
  $lines.Add("/obs unlit pass light")
  $lines.Add("/obs unlit pass stalker")
  $lines.Add("/obs unlit pass extinguish")
  $lines.Add("/obs unlit pass house")
  $lines.Add("/obs unlit pass extract")
  $lines.Add('```')
  $lines.Add("")
  $lines.Add("6. Verify all eight Unlit houses: lamp, cairn, coop, well, watch, warm, threshold, and base.")
  $lines.Add("7. Check every media artifact before flipping flags. Use " + (Code "manual-media-checklist.md") + ". Do not point a player to a missing clip, zip, spectrogram, Discord clue, or dashboard route.")
  $lines.Add("8. Flip media flags only after the artifact is reachable from a normal player context:")
  $lines.Add("")
  $lines.Add('```text')
  $lines.Add("/observance flag set media_clip_01_ready true")
  $lines.Add("/observance flag set media_clip_02_ready true")
  $lines.Add("/observance flag set media_clip_03_ready true")
  $lines.Add("/observance flag set media_clip_04_ready true")
  $lines.Add("/observance flag set recovered_archive_ready true")
  $lines.Add('```')
  $lines.Add("")
  $lines.Add("9. Run a real first-hour pass with no operator hints. A player must be able to discover the next destination from player-facing evidence.")
  $lines.Add("10. Run a late-game pass with the co-op vault, Failed Accepting, Accepting rite, Wren reckoning, Record/dashboard handoff, and final release/erase choice.")
  $lines.Add("10a. Failed Accepting is launch-blocking: the prior camp must be physically gated, filled with readable evidence, solvable in parallel, retraceable after partial progress, and required before the finale. Record proof in " + (Code "Failed Accepting Proof") + " and " + (Code "launch-attestations.md") + ".")
  $lines.Add("11. Complete " + (Code "00-notes.md") + ", " + (Code "fixes.md") + ", " + (Code "launch-attestations.md") + ", screenshots, and clips.")
  $lines.Add("")
  $lines.Add("## Scenario Stress List")
  $lines.Add("")
  $lines.Add("Run these as spot checks during vertical slice and full rehearsal. Record failures in " + (Code "fixes.md") + ".")
  $lines.Add("")
  foreach ($scenario in @(
    "new player joins late and still knows where the group is",
    "player refuses resource pack",
    "player submits answer with punctuation/case/extra spaces",
    "player edits labelled/flavor sign instead of blank answer sign",
    "two players submit at once",
    "player dies during a clue route",
    "player logs out inside Unlit",
    "group splits across dimensions",
    "operator is offline for ten minutes",
    "Discord hint arrives before the related Minecraft evidence",
    "dashboard page is opened before the intended flag",
    "media flag is false and the clue remains withheld",
    "media flag is true and the artifact is reachable",
    "Wren is missing or Citizens is absent",
    "townsfolk are missing",
    "wrong Supabase key",
    "Supabase writes queue instead of flushing",
    "server restart after sites are placed",
    "datapack disabled after restart",
    "Unlit has stray torches or too much ambient light",
    "borrowed lantern breaks and player needs recovery",
    "players brute-force keeper order",
    "players skip side lore and hit finale gate early",
    "players finish keeper stones but the old camp/Failed Accepting gate does not stop the finale",
    "players enter the old camp before filing no witness",
    "players solve a prior repair by hint wording without finding supporting evidence",
    "players try to speedrun with coordinates from another player",
    "players ask where to go next after every required movement",
    "wrong answer feedback accidentally gives the solution",
    "right answer feedback is too vague",
    "NPC line claims a physical object that is not present",
    "book/sign text is illegible on default GUI scale",
    "custom rune font fails or falls back",
    "co-op gate with one player absent",
    "co-op gate with players desynced by latency",
    "Accepting rite at the wrong hour",
    "Accepting rite with incomplete evidence",
    "finale choice repeated after restart"
  )) {
    $lines.Add("- [ ] " + $scenario)
  }
  $lines.Add("")
  $lines.Add("## Stop Conditions")
  $lines.Add("")
  $lines.Add("Stop the test and fix the repo/world if any of these happen:")
  $lines.Add("")
  $lines.Add("- A required movement has no player-facing pointer.")
  $lines.Add("- A side path is interesting but irrelevant.")
  $lines.Add("- An NPC, book, sign, Discord hint, dashboard page, or media artifact contradicts another surface.")
  $lines.Add("- Operator explanation is required for answer format, destination, or mechanic fairness.")
  $lines.Add("- A major build reads as sign-with-clue/sign-with-input rather than a place.")
  $lines.Add("- The old camp opens without " + (Code "no witness") + ", or the finale opens without " + (Code "witness before accepting") + ".")
  $lines.Add("- Any outside-Hold launch coordinate is a placeholder, any Deep Hold row lacks GeneratedProof, or any launch row lacks approach/focal/action/exit proof.")
  $lines.Add("- Resource pack, datapack, Supabase, Discord, or dashboard behavior differs between operator and normal player contexts.")
  $lines.Add("- Consent/capture/credential tasks are incomplete for any player-facing rehearsal.")
  $lines.Add("")
  $lines.Add("## Final Commands")
  $lines.Add("")
  $lines.Add("Draft rehearsal packet check:")
  $lines.Add("")
  $lines.Add('```powershell')
  $lines.Add("powershell -NoProfile -ExecutionPolicy Bypass -File tools\check_rehearsal_packet.ps1 -PacketDir `"" + $RehearsalDir + "`" -AllowOpenItems")
  $lines.Add('```')
  $lines.Add("")
  $lines.Add("Final launch-strength blocker gate:")
  $lines.Add("")
  $lines.Add('```powershell')
  $lines.Add("powershell -NoProfile -ExecutionPolicy Bypass -File tools\check_launch_manual_blockers.ps1 -Launch -CaptureCsv `"" + $CaptureCsv + "`" -RehearsalPacket `"" + $RehearsalDir + "`"")
  $lines.Add('```')
  $lines.Add("")
  $lines.Add("Verdict rule: a smoke or vertical-slice pass can justify more testing. Only the launch-strength blocker gate plus completed real-player evidence can justify launch.")

  [System.IO.File]::WriteAllLines($guidePath, $lines, [System.Text.UTF8Encoding]::new($false))
  return $guidePath
}

$repoFull = [System.IO.Path]::GetFullPath($RepoRoot)
$tools = Join-Path $repoFull "tools"
$friendPrep = Join-Path $tools "prepare_friend_launch.ps1"
if (-not (Test-Path $friendPrep)) {
  throw "server test prep: missing required helper: $friendPrep"
}

$friendArgs = @("-RepoRoot", $repoFull, "-Date", $Date)
if (-not [string]::IsNullOrWhiteSpace($ResourcePackUrl)) {
  $friendArgs += @("-ResourcePackUrl", $ResourcePackUrl)
}
if ($SkipBundle) { $friendArgs += "-SkipBundle" }
if ($Force) { $friendArgs += "-Force" }

Write-Host "== Create base launch/rehearsal packets =="
& powershell -NoProfile -ExecutionPolicy Bypass -File $friendPrep @friendArgs
if ($LASTEXITCODE -ne 0) {
  exit $LASTEXITCODE
}

$placementDir = Join-Path (Join-Path $repoFull "build\launch-placement") $Date
$captureCsv = Join-Path $placementDir "coords-capture.csv"
$rehearsalDir = Join-Path (Join-Path $repoFull "rehearsals") $Date
if (-not (Test-Path $placementDir)) {
  throw "server test prep: expected placement packet was not created: $placementDir"
}
if (-not (Test-Path $rehearsalDir)) {
  throw "server test prep: expected rehearsal packet was not created: $rehearsalDir"
}

$guide = Write-ServerTestGuide $repoFull $Date $placementDir $captureCsv $rehearsalDir $ResourcePackUrl ([bool]$SkipBundle)

Write-Host ""
Write-Host "server test prep ready:"
Write-Host "  guide:              $guide"
Write-Host "  placement packet:   $placementDir"
Write-Host "  coordinate capture: $captureCsv"
Write-Host "  rehearsal packet:   $rehearsalDir"
Write-Host ""
Write-Host "use the guide's Test Depths section to choose smoke, vertical slice, full rehearsal, or launch go/no-go."
